<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-16 at 18:52:22.
 */
class QuoteItemCategoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var QuoteItemCategory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new QuoteItemCategory ("Linguistic");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers QuoteItemCategory::renderXml
     * @todo   Implement testRenderXml().
     */
    public function testRenderXml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers QuoteItemCategory::setShouldPrintXml
     * @todo   Implement testSetShouldPrintXml().
     */
    public function testSetShouldPrintXml() {
        $this->object->setShouldPrintXml(true);
        $this->assertEquals(
            true, $this->object->shouldPrintXml()
        );
        $this->object->setShouldPrintXml(false);
        $this->assertEquals(
            false, $this->object->shouldPrintXml()
        );
    }

    /**
     * @covers QuoteItemCategory::thisSupportsXmlPrinting
     * @todo   Implement testThisSupportsXmlPrinting().
     */
    public function testThisSupportsXmlPrinting() {
        $this->assertEquals(
            true, $this->object->thisSupportsXmlPrinting()
        );
        
        $this->object = new QuoteItemCategory ("Quality Assurance");
        $this->assertEquals(
            false, $this->object->thisSupportsXmlPrinting()
        );
    }

    /**
     * @covers QuoteItemCategory::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        $this->assertEquals(
            'Linguistic', $this->object->getName()
        );
    }

    /**
     * @covers QuoteItemCategory::putLineItem
     * @todo   Implement testPutLineItem().
     */
    public function testPutLineItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
